site_name: SemanticMemes
nav:
  - Home: index.md
  - About: about.md
  - Publications: publications.md
  - Dataset: dataset.md
  - Annotation Site: annotation-site.md
theme: readthedocs
extra_css: [extra.css]
markdown_extensions:
  - markdown.extensions.attr_list